name: Build Packages

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided

  mac:
    # Name the Job
    name: MacOS
    # Set the type of machine to run on
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm run make
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: MacOS .app
        path: |
          out/make/zip/darwin/x64/*.zip

  ubuntu:
    # Name the Job
    name: Ubuntu
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm run make
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Ubuntu .deb
        path: |
          out/*/*.deb

  win:
    # Name the Job
    name: Windows
    # Set the type of machine to run on
    runs-on: windows-latest

    # Runs the Super-Linter action
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm run make
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Windows .exe
        path: |
          out/*/*.exe
